codestates-seb/seb43_main_001

server/build.gradle, server/src/main/java/main001/server/ServerApplication.java, server/src/main/java/main001/server/audit/BaseTimeEntity.java, server/src/main/java/main001/server/domain/portfoliocomment/controller/PortfolioCommentController.java, server/src/main/java/main001/server/domain/portfoliocomment/dto/PortfolioCommentDto.java, server/src/main/java/main001/server/domain/portfoliocomment/entity/PortfolioComment.java, server/src/main/java/main001/server/domain/portfoliocomment/mapper/PortfolioCommentMapper.java, server/src/main/java/main001/server/domain/portfoliocomment/repository/PortfolioCommentRepository.java, server/src/main/java/main001/server/domain/portfoliocomment/service/PortfolioCommentService.java, server/src/main/java/main001/server/domain/usercomment/controller/UserCommentController.java, server/src/main/java/main001/server/domain/usercomment/dto/UserCommentDto.java, server/src/main/java/main001/server/domain/usercomment/entity/UserComment.java, server/src/main/java/main001/server/domain/usercomment/mapper/UserCommentMapper.java, server/src/main/java/main001/server/domain/usercomment/repository/UserCommentRepository.java, server/src/main/java/main001/server/domain/usercomment/service/UserCommentService.java
- 유저에게 작성하는 댓글 API구현
- 포트폴리오에 작성하는 댓글 API 구현
- 모든 도메인에 적용되는 auditing기능 구현
=> Feat : "UserComment/PortfolioComment/auditing 구현"

server/src/main/java/main001/server/domain/user/advice/ErrorResponse.java, server/src/main/java/main001/server/domain/user/advice/GlobalExceptionAdvice.java, server/src/main/java/main001/server/domain/user/controller/UserController.java, server/src/main/java/main001/server/domain/user/dto/UserDto.java, server/src/main/java/main001/server/domain/user/entity/User.java, server/src/main/java/main001/server/domain/user/enums/Grade.java, server/src/main/java/main001/server/domain/user/enums/JobStatus.java, server/src/main/java/main001/server/domain/user/enums/UserStatus.java, server/src/main/java/main001/server/domain/user/exception/BusinessLogicException.java, server/src/main/java/main001/server/domain/user/exception/ExceptionCode.java, server/src/main/java/main001/server/domain/user/mapper/UserMapper.java, server/src/main/java/main001/server/domain/user/pagenation/MultiResponseDto.java, server/src/main/java/main001/server/domain/user/pagenation/PageInfo.java, server/src/main/java/main001/server/domain/user/pagenation/SingleResponseDto.java, server/src/main/java/main001/server/domain/user/repository/UserRepository.java, server/src/main/java/main001/server/domain/user/service/UserService.java, server/src/main/java/main001/server/domain/user/utils/UriCreator.java
User Entity를 구현했습니다.
-Entity
-Repository
-Service
-Controller
-Dto
-Mapper
-Util: Paging, Advice, URI, Exception
Issue #4
closes #4
=> Feat: UserEntity 구현

server/src/main/java/main001/server/domain/user/dto/UserDto.java, server/src/main/java/main001/server/domain/user/entity/User.java, server/src/test/java/main001/server/domain/user/controller/UserControllerTest.java
- Post User 테스트
- Get User 테스트
- Get Users 테스트
- Patch User 테스트
- Delete User 테스트
- 기타 오류 수정(User, UserDto) Issue #8
closes #8
=> Feat: UserEntity 테스트 및 리팩토링#8

client/src/store/slice/themeSlice.ts
fe-feat/헤더컴포넌트/#10 => fe
- test용으로 수정 진행
=> comment:불필요한 코드들 제거 및 정리

client/src/components/common/icons.tsx
fe-feat/icons/#16 => fe
public/assets에 있는 icon => components/common/icon.tsx에 통합
=> refactor: icons 설정#16

client/src/components/common/button.style.tsx, client/src/components/common/button.tsx, client/src/constants/index.ts, client/src/layout/header/Hamburger.style.tsx, client/src/layout/header/Hamburger.tsx, client/src/layout/header/Header.style.tsx, client/src/layout/header/Header.tsx, client/src/layout/header/Toggle.style.tsx, client/src/layout/header/Toggle.tsx, client/src/style/theme.ts
Fe feat/헤더컴포넌트/#10 => fe
전반적인 레이아웃을 잡기 위해 아직 반응형은 완전히 구현되지 않은 상태 추가 적용 예정
=> design:헤더 레이아웃 구현

client/src/components/Login/LoginContainer.style.tsx, client/src/components/Login/LoginContainer.tsx, client/src/components/Login/OAuthBtn.style.tsx, client/src/components/Login/OAuthBtn.tsx, client/src/pages/Login.tsx
fe-feat/login/#18 => fe
로고, 프로젝트 이름 추후 교체 필요
<p>태그 안에 줄 바꿈 적용이 안되서 추후 적용 필요
반응형에 따라 margin을 다르게 적용하여 배치 조절 완료
=> design:로그인 레이아웃 구현

client/src/components/common/button.style.tsx, client/src/layout/header/NavLink.style.tsx, client/src/pages/Detail.tsx, client/src/store/slice/themeSlice.ts, client/src/style/GlobalStyle.ts
fe-feat/헤더컴포넌트/#10 => fe
button에 background transparent와 border:0을 추가했습니다!
=> design: global 스타일 속성 추가

client/src/layout/footer/Footer.style.tsx, client/src/layout/footer/Footer.tsx
fe-feat/footer/#19 => fe
- 서비스 소개, 문의하기 페이지가 없어서 페이지 연결은 하지 않았습니다.
=> design: footer 컴포넌트 구현

client/src/pages/NotFound.style.ts, client/src/pages/NotFound.tsx, client/src/router.tsx
fe-feat/notFound/#42 => fe
- router.tsx에 not found 페이지 추가
=> design: Not Found 페이지 구현

client/src/components/Detail/Comment.style.tsx, client/src/components/Detail/Comment.tsx, client/src/components/Detail/CommentItem.style.tsx, client/src/components/Detail/CommentItem.tsx, client/src/components/Detail/ProjectImg.style.tsx, client/src/components/Detail/ProjectImg.tsx, client/src/components/Detail/mock.ts, client/src/layout/header/Header.style.tsx, client/src/pages/Detail.style.tsx
fe-feat/상세페이지/#32 => fe
더미 데이터 생성 및 사용자 comment 부분 추가 수정
=> design:Detail comment 부분 추가 수정

client/package-lock.json, client/package.json, client/src/components/Portfolio/DetailBox.style.tsx, client/src/components/Portfolio/DetailBox.tsx, client/src/components/Portfolio/ImgBox.style.tsx, client/src/components/Portfolio/ImgBox.tsx, client/src/components/Portfolio/NewPortfolioContainer.style.tsx, client/src/components/Portfolio/NewPortfolioContainer.tsx, client/src/components/Portfolio/TagBox.style.tsx, client/src/components/Portfolio/TagBox.tsx, client/src/components/Portfolio/TextBox.style.tsx, client/src/components/Portfolio/TextBox.tsx, client/src/components/Portfolio/TextareaBox.style.tsx, client/src/components/Portfolio/TextareaBox.tsx, client/src/components/Portfolio/UserBox.style.tsx, client/src/components/Portfolio/UserBox.tsx, client/src/pages/Portfolio.style.tsx, client/src/pages/Portfolio.tsx, client/src/router.tsx
fe-feat/포트폴리오 작성/#36 => fe
- 이미지 선택, 태그 기능, 상세 정보 기능(웹 에디터) 기능들을 구현했습니다.
- 태그의 초기값이 빈 배열일 때, 타입 오류가 발생하여 수정이 필요합니다.
- React-quill 에디터 내에서 기능이 적용안되는 현상이 있어서 수정이 필요합니다
- 중복되는 코드들이 있는지 추가적으로 검토가 필요합니다.
=> design: 포트폴리오 작성 페이지 추가

client/src/components/Login/LoginContainer.style.tsx, client/src/components/Login/LoginContainer.tsx, client/src/components/Portfolio/DetailBox.tsx
=> refactor: 코드 정리

client/src/components/User/Feedback.style.ts, client/src/components/User/Feedback.tsx, client/src/components/User/FeedbackContainer.style.ts, client/src/components/User/Portfolio.style.ts, client/src/components/User/Portfolio.tsx, client/src/components/User/UserBasicInfo.style.ts, client/src/components/User/UserBasicInfo.tsx, client/src/components/User/UserEditForm.style.ts, client/src/components/User/UserEditForm.tsx, client/src/components/User/UserInfo.style.ts, client/src/components/User/mock.ts
fe-feat/유저페이지/#20 => fe
- 버튼 크기 수정
- 피드백에 날짜 추가
- 수정시 이미지 CSS 추가
- BasicInfo 의 간격 조정
- input에 placeholder 추가
=> design: 버튼 크기 등 CSS 수정

client/src/components/Home/Search.style.ts, client/src/components/Home/Search.tsx
=> fix: 모바일과 데스크탑 브라우저에서 input이 다르게 보이는 버그 수정

client/src/components/User/UserBasicInfo.style.ts, client/src/components/User/UserBasicInfo.tsx, client/src/components/User/UserEditForm.style.ts, client/src/components/User/UserEditForm.tsx
fe-feat/유저페이지/#20 => fe
- 유저 이름 변경 추가
- 유저 이메일 수정 사항을 공개/비공개로 수정
=> feat: 수정사항 변경

client/src/pages/AddEmail.style.ts, client/src/pages/AddEmail.tsx, client/src/router.tsx
fe-feat/이메일등록/#66 => fe
이메일 등록 페이지 레이아웃 구현
라우터 연결 완료
=> design: AddEmail 페이지 레이아웃 구현

client/src/store/index.ts, client/src/store/slice/loginSlice.ts
fe-feat/로그인 페이지/#62 => fe
redux persist를 이용한 login, token 전역 상태관리 기능 추가
=> feat: redux-persist를 이용한 로그인,토큰 상태관리 기능 구현

server/build.gradle, server/src/main/java/main001/server/domain/user/controller/UserController.java, server/src/main/java/main001/server/domain/user/dto/UserDto.java, server/src/main/java/main001/server/domain/user/entity/User.java, server/src/main/java/main001/server/domain/user/mapper/UserMapper.java, server/src/main/java/main001/server/domain/user/service/UserService.java, server/src/main/java/main001/server/security/WebConfig.java, server/src/main/java/main001/server/security/config/SecurityConfiguration.java, server/src/main/java/main001/server/security/controller/OAuthController.java, server/src/main/java/main001/server/security/dto/LoginDto.java, server/src/main/java/main001/server/security/filter/JwtAuthenticationFilter.java, server/src/main/java/main001/server/security/filter/JwtVerificationFilter.java, server/src/main/java/main001/server/security/handler/MemberAccessDeniedHandler.java, server/src/main/java/main001/server/security/handler/MemberAuthenticationEntryPoint.java, server/src/main/java/main001/server/security/handler/MemberAuthenticationFailureHandler.java, server/src/main/java/main001/server/security/handler/MemberAuthenticationSuccessHandler.java, server/src/main/java/main001/server/security/handler/OAuth2UserSuccessHandler.java, server/src/main/java/main001/server/security/jwt/JwtTokenizer.java, server/src/main/java/main001/server/security/userdetails/MemberDetailsService.java, server/src/main/java/main001/server/security/utils/CustomAuthorityUtils.java, server/src/main/java/main001/server/security/utils/ErrorResponder.java, server/src/main/resources/application.yml, server/src/test/java/main001/server/domain/user/controller/UserControllerRestDocsTest.java
- SpringSecurity
- OAuth2
- jwt
- User DTO 분리(user, userprofile)
issue #22
=> Feat: SecurityOAuth2#22

client/src/components/Login/LoginContainer.tsx, client/src/store/slice/loginSlice.ts
fe-feat/로그인 페이지/#62 => fe
로그인 시 accessToken,refreshToken 받기 기능 구현
loginSlice 전역 상태 수정 및 타입 지정
=> feat: 로그인 시, token 받기 기능 구현

client/src/components/Login/OAuthBtn.tsx
fe-feat/로그인 페이지/#62 => fe
참고 사항
OAuth 버튼 기능 추가(클릭 시 로그인)
=> feat: Oauth 버튼 기능 추가

client/src/components/Home/Banner.tsx, client/src/components/common/Card.tsx, client/src/router.tsx
=> feat: Detail 페이지 path 경로에 id 추가 

server/src/main/java/main001/server/domain/user/service/UserService.java, server/src/main/java/main001/server/security/handler/OAuth2UserSuccessHandler.java
- OAuth 로그인 분기 처리
- 기존 사용자 -> redirect home("/")
- 이메일 "null" -> redirect addemail("/addemail")
- 관련 UserService 메서드 추가(IsExistEmail) Issue #79
=> Feat: SecurityOAuth2 기능 추가#79

server/src/main/java/main001/server/domain/user/dto/UserDto.java, server/src/main/java/main001/server/domain/user/mapper/UserMapper.java, server/src/main/java/main001/server/domain/user/service/UserService.java, server/src/main/java/main001/server/security/controller/OAuthController.java, server/src/main/java/main001/server/security/handler/OAuth2UserSuccessHandler.java
OAuth2 기능 수정
- addemail redirect관련
- addemail관련 controller 구현
issue #83
=> Feat: OAuth2 기능 수정

client/src/components/Login/LoginContainer.tsx, client/src/components/Login/OAuthBtn.style.tsx
fe-feat/로그인페이지/#62 => fe
구글 OAuth 로그인 기능 추가
=> feat: 로그인 페이지: 구글 로그인 기능 구현

client/src/pages/AddEmail.style.ts, client/src/pages/AddEmail.tsx
fe-feat/addEmail/#66 => fe
서버로 이메일 전송 기능 추가했습니다
=> feat: 이메일 추가 페이지: 이메일 전송 기능 추가

server/src/main/resources/application-local.yml
=> Fix:application.yml

client/src/components/Login/LoginContainer.tsx
fe-feat/로그인 페이지/#62 => fe
구글 로그인 버튼 onClick 함수 수정
=> fix: 구글 로그인 버튼 onClick 함수 수정

server/src/main/java/main001/server/domain/portfolio/dto/PortfolioDto.java, server/src/main/java/main001/server/domain/portfolio/mapper/PortfolioMapper.java, server/src/main/java/main001/server/domain/portfoliocomment/dto/PortfolioCommentDto.java, server/src/main/java/main001/server/domain/portfoliocomment/mapper/PortfolioCommentMapper.java, server/src/main/java/main001/server/domain/user/dto/UserDto.java, server/src/main/java/main001/server/domain/user/mapper/UserMapper.java, server/src/main/java/main001/server/domain/usercomment/dto/UserCommentDto.java, server/src/main/java/main001/server/domain/usercomment/mapper/UserCommentMapper.java
각 페이지 IsAuth 추가
- portfolio
- portfolioComment
- userComment
issue #101
=> Feat: 각 페이지 IsAuth 추가

client/src/components/Login/LoginContainer.tsx
fe-feat/로그인 페이지/https://github.com/codestates-seb/seb43_main_001/issues/62 => fe
구글 로그인 url 수정
=> fix: 구글 로그인 url 수정

client/src/api/client.ts, client/src/components/Detail/Comment.tsx, client/src/components/Detail/CommentItem.tsx, client/src/components/Detail/Description.tsx, client/src/components/Detail/DetailTitle.tsx, client/src/hooks/useGetPortfolio.ts, client/src/hooks/useGetPortfolioComment.ts, client/src/hooks/useIncreasePageView.ts, client/src/hooks/usePatchPortfolioComment.ts, client/src/hooks/usePostPortfolioComment.ts, client/src/pages/Detail.tsx, client/src/router.tsx, client/src/store/slice/loginSlice.ts, client/src/types/index.ts, client/src/utils/getAccessToken.ts, client/src/utils/getUserIdFromAccessToken.ts
fe-feat/상세페이지/#68
- loginSlice 코드 수정
- client axios 수정
=> feat: custom axios 코드 수정 및 redux 기능 추가

server/src/main/java/main001/server/security/config/SecurityConfiguration.java, server/src/main/java/main001/server/security/jwt/RefreshToken.java
=> Feat: OAuth2관련 기능 수정

client/src/api/client.ts, client/src/components/Detail/Comment.tsx, client/src/components/Detail/CommentItem.style.ts, client/src/components/Detail/CommentItem.tsx, client/src/components/Detail/Description.tsx, client/src/components/Detail/DetailTitle.style.ts, client/src/components/Detail/DetailTitle.tsx, client/src/components/Detail/ProjectContent.tsx, client/src/components/Detail/ProjectImg.tsx, client/src/hooks/useDeletePortfolioComment.ts, client/src/hooks/useGetPortfolio.ts, client/src/hooks/usePatchPortfolioComment.ts, client/src/hooks/usePostPortfolioComment.ts, client/src/layout/header/Header.tsx, client/src/pages/Detail.style.ts, client/src/pages/Detail.tsx, client/src/types/index.ts
- rickyshu/fe =>fe
- client 헤더 토큰 저장 방식 수정
- level 1까지의 내용들 보완 완료
=> feat:상세페이지 AJAX 요청 level 1 완료

client/src/api/client.ts, client/src/components/Detail/CommentItem.tsx, client/src/components/Detail/DetailTitle.style.ts, client/src/components/Detail/DetailTitle.tsx, client/src/hooks/useDeletePortfolioComment.ts, client/src/pages/Home.tsx, client/src/utils/getUserIdFromAccessToken.ts
=> feat:API TokenClient 수정 및 UI 수정

client/src/components/Portfolio/PortfolioContainer.tsx, client/src/components/Portfolio/UserBox.tsx, client/src/pages/EditPortfolio.tsx, client/src/pages/NewPortfolio.tsx
fe-feat/포트폴리오 생성페이지/https://github.com/codestates-seb/seb43_main_001/issues/63 => fe
useGetUserProfile 훅에서 받아오는 UserInfo -> UserProfile로 네이밍 수정
=> rename: UserInfo -> UserProfile로 네이밍 수정

server/src/main/java/main001/server/domain/user/controller/UserController.java, server/src/main/java/main001/server/domain/user/service/UserService.java, server/src/main/java/main001/server/security/repository/RefreshTokenRepository.java, server/src/main/java/main001/server/security/service/SecurityService.java, server/src/main/java/main001/server/security/service/SecurityServiceImpl.java
- ProfileImg 업로드 기능 버그 수정
- addEmail 연관관계관련 버그 수정 Issue #129
=> Fix: ProfileImg&addEmail 버그 수정#129

client/src/router.tsx, client/src/utils/loaderAuth.ts
fe-feat/home/#71 => fe
* 로그인 안했을때 접근 못하는 페이지: NewPortfolio, EditPortfolio
=> feat: 로그인 유무에 따른 페이지 접근 제한 기능 추가

client/src/layout/GeneraLayout.tsx
=> feat: GeneraLayout에 Outlet 추가

server/src/main/java/main001/server/domain/user/controller/UserController.java, server/src/main/java/main001/server/domain/user/entity/User.java, server/src/main/java/main001/server/domain/user/service/UserService.java, server/src/main/java/main001/server/domain/utils/CurrentUserIdFinder.java, server/src/main/java/main001/server/security/handler/OAuth2UserSuccessHandler.java, server/src/main/java/main001/server/security/jwt/RefreshToken.java, server/src/main/java/main001/server/security/repository/RefreshTokenRepository.java, server/src/main/java/main001/server/security/service/SecurityServiceImpl.java
User&Security 기능 수정 및 추가
- user : isAuth 기능 수정
- security : RefreshToken 연관관계 수정 
Issue #138
closes #138
=> Feat: User&Security 기능 수정 및 추가

client/src/pages/EditPortfolio.tsx, client/src/pages/NewPortfolio.tsx, client/src/store/slice/loginSlice.ts
fe-feat/newPortfolio/#71 => fe
* Login 전역 상태 token값 저장 기능 제거 및 관련 기능 삭제
*관련 페이지 오류 수정(EditPortfolio,NewPortfolio)
=> fix: Login 전역 상태 token값 저장 기능 제거 및 관련 오류 수정

client/src/api/client.ts, client/src/components/Detail/LikeBtn.style.ts, client/src/components/Detail/LikeBtn.tsx, client/src/components/Detail/ProjectContent.style.ts, client/src/components/Detail/ProjectContent.tsx, client/src/components/Detail/ProjectImg.tsx, client/src/components/SignUp/SignInput.style.ts, client/src/components/SignUp/SignInput.tsx, client/src/components/SignUp/SignupForm.style.ts, client/src/components/SignUp/SignupForm.tsx, client/src/hooks/useLikeBtn.ts, client/src/hooks/usePostPortfolioComment.ts, client/src/layout/header/Header.tsx, client/src/layout/header/NavLink.tsx, client/src/layout/main/Main.style.tsx, client/src/pages/Detail.tsx, client/src/pages/Home.tsx, client/src/pages/SignUp.style.ts, client/src/pages/SignUp.tsx, client/src/router.tsx, client/src/store/slice/loginSlice.ts, client/src/types/index.ts
- rickyshu/fe  => fe
- 좋아요 기능 추가 
- 회원가입 페이지 레이아웃 구현
=> design: SignUp page 레이아웃 완성

client/src/api/client.ts, client/src/components/Login/LoginContainer.tsx, client/src/pages/AddEmail.tsx
fe-feat/AddEmail#66 => fe
* 깃허브 로그인시 이메일 추가 기능 구현 
* 관련 API 수정 및 api 디렉토리로 이동하여 관리
=> feat: 깃허브 로그인시 이메일 추가 기능 구현 및 API 수정

client/src/api/client.ts, client/src/components/Detail/LikeBtn.style.ts, client/src/components/Detail/LikeBtn.tsx, client/src/hooks/useLikeBtn.ts, client/src/layout/header/Header.style.tsx, client/src/layout/header/Header.tsx
fe-feat/상세페이지/#123 => fe
- 좋아요 버튼 수정
- 로그아웃 localstorage 토큰 삭제 기능 추가
- 토큰 딜레이 버그 수정
=> fix:좋아요,로그아웃,토큰 버그 수정

server/src/main/java/main001/server/domain/portfolio/controller/PortfolioController.java, server/src/main/java/main001/server/domain/user/controller/UserController.java, server/src/main/java/main001/server/domain/user/mapper/UserMapper.java, server/src/main/java/main001/server/security/controller/SecurityController.java
=> Fix: SecurityController 수정

server/src/main/java/main001/server/domain/user/controller/UserController.java, server/src/main/java/main001/server/domain/utils/CurrentUserIdFinder.java
NullPointException 수정
Issue #156
=> Fix: IsAuth NullPointException 수정 #156

server/src/main/java/main001/server/config/EnvConfig.java, server/src/main/java/main001/server/domain/portfolio/controller/PortfolioController.java, server/src/main/java/main001/server/domain/portfolio/mapper/PortfolioMapper.java, server/src/main/java/main001/server/domain/portfolio/service/PortfolioService.java, server/src/main/java/main001/server/domain/portfoliocomment/dto/PortfolioCommentDto.java, server/src/main/java/main001/server/domain/portfoliocomment/mapper/PortfolioCommentMapper.java, server/src/main/java/main001/server/domain/user/controller/UserController.java, server/src/main/java/main001/server/domain/user/mapper/UserMapper.java, server/src/main/java/main001/server/domain/usercomment/dto/UserCommentDto.java, server/src/main/java/main001/server/domain/usercomment/mapper/UserCommentMapper.java, server/src/main/java/main001/server/domain/utils/CurrentUserIdFinder.java, server/src/main/java/main001/server/security/controller/SecurityController.java, server/src/main/java/main001/server/security/filter/JwtAuthenticationFilter.java, server/src/main/java/main001/server/security/handler/OAuth2UserSuccessHandler.java, server/src/main/resources/application-local.yml, server/src/main/resources/application-server.yml
- IsAuth 기능 수정
- Login 기능 수정 Issue #159
=> Feat: IsAuth 및 Login 기능 수정

server/src/main/resources/application-server.yml
application-server 수정
- 띄어쓰기 오류 issue #159
=> Fix: application-server 수정

client/src/components/User/CommentContainer.tsx, client/src/components/User/CommentItem.style.ts, client/src/components/User/CommentItem.tsx, client/src/components/User/Portfolio.style.ts, client/src/components/User/Portfolio.tsx, client/src/components/User/UserBasicInfo.style.ts, client/src/components/User/UserBasicInfo.tsx, client/src/components/User/UserInfo.style.ts, client/src/components/User/UserInfo.tsx, client/src/components/common/Button.style.ts, client/src/types/index.ts
fe-feat/유저페이지/#70 => fe
- 유저 댓글 임시 Auth 기능 추가(작성자, 페이지 유저에 따른 버튼 표시 유무)
- 유저 댓글 링크 아이콘 표시 변경(받은 댓글의 경우 링크 아이콘이 나타나지 않음)
- resize 이벤트에 따른 state 변경 추가(데스크탑 화면에선 포트폴리오 컴포넌트가 두 개 나타나는 오류 수정)
- width, height 등의 UI 일부 조정
=> feat: 유저 댓글 임시 Auth 기능 추가, Link 아이콘 표시 변경

client/src/components/common/Card.style.ts
=> fix: 카드 소개글 줄바꿈 처리

client/src/api/client.ts, client/src/components/Detail/DetailTitle.tsx, client/src/hooks/useDeletePortfolio.ts, client/src/pages/Detail.tsx
=> feat: 상세페이지 수정 및 삭제 기능 추가

client/src/layout/footer/Footer.tsx, client/src/layout/footer/HelpModal.style.ts, client/src/layout/footer/HelpModal.tsx
=> feat: 문의하기 모달 추가

client/src/api/client.ts, client/src/components/Login/LoginContainer.style.tsx, client/src/components/Login/LoginContainer.tsx, client/src/components/Login/OAuthBtn.style.tsx, client/src/components/Login/OAuthBtn.tsx, client/src/hooks/usePostUserLogin.ts, client/src/types/index.ts
fe-feat/login/#62 => fe
login 타입 및 관련 훅 생성
Email & pw 로그인 기능 구현 (서버에서 메인으로 리다이렉션은 안되는 중 + 토큰 값을 받아오지 못하는 문제)
loginPage 레이아웃 수정
=> feat: email&pw 로그인 기능 추가 및 화면 레이아웃 변경

server/src/main/java/main001/server/security/handler/MemberAuthenticationSuccessHandler.java
=> Fix: Login 기능 수정#169

server/src/main/java/main001/server/domain/user/entity/User.java, server/src/main/java/main001/server/domain/user/service/UserService.java, server/src/main/java/main001/server/security/handler/MemberAuthenticationSuccessHandler.java
- UserProfileImg 기본 이미지 적용 Issue #180
=> Fix: UserProfileImg 수정#180

client/public/index.html, client/src/api/client.ts, client/src/components/Detail/Description.style.ts, client/src/components/Detail/DetailTitle.style.ts, client/src/components/Detail/DetailTitle.tsx, client/src/components/Detail/ProjectContent.style.ts, client/src/components/Detail/ProjectImg.style.ts, client/src/components/Detail/ProjectImg.tsx, client/src/components/common/Card.style.ts, client/src/hooks/useGetPortfolioList.ts, client/src/layout/header/Header.tsx, client/src/pages/Detail.tsx, client/src/style/GlobalStyle.ts, client/src/types/index.ts
fe/rickyshu => fe
- 종합 에러 수정
- 상세 페이지 디자인 수정
- toast 에러 수정
=> fix:종합 에러 수정

client/src/hooks/usePostUserLogin.ts
fe-feat//login/#189 => fe
- 리다이렉션 로그인 방식에서, 로그인 성공 시 access,refreshToken 받아오는 방식으로 변경
- email 로그인 기능 정상 작동
=> fix: 헤더에서 토큰을 받아오는 방식으로 email 로그인 수정

server/src/main/java/main001/server/domain/portfolio/entity/Portfolio.java, server/src/main/java/main001/server/domain/user/service/UserService.java, server/src/main/java/main001/server/exception/ExceptionCode.java, server/src/main/java/main001/server/security/handler/OAuth2UserSuccessHandler.java
=> Fix: OAuth2 addemail 수정#187

server/src/main/java/main001/server/domain/user/controller/UserController.java, server/src/main/java/main001/server/domain/user/dto/UserDto.java, server/src/main/java/main001/server/domain/user/mapper/UserMapper.java, server/src/main/java/main001/server/domain/user/service/UserService.java, server/src/main/java/main001/server/security/controller/SecurityController.java
- Email 중복 체크 기능 구현 Issue #198
=> Feat: UserEmail Check#198

client/src/components/User/CommentItem.style.ts, client/src/components/User/CommentItem.tsx, client/src/components/User/UserBasicInfo.tsx, client/src/components/common/ConfirmationModal.style.ts
fe-feat/유저페이지/#70 => fe
- 댓글 삭제 클릭 시 확인 절차 추가
- 유저 페이지의 Follow, views 표시 제거(주석처리)
- 모달의 텍스트 컬러 수정(다크모드에서도 변동하지 않도록 변경)
=> feat: 댓글 삭제 확인 과정 추가

client/src/components/Detail/ProjectContent.tsx, client/src/components/Portfolio/DetailBox.tsx, client/src/components/Portfolio/Editor.style.ts, client/src/components/Portfolio/Editor.tsx, client/src/components/Portfolio/PortfolioContainer.tsx, client/src/components/Portfolio/TagBox.style.ts, client/src/components/Portfolio/TagBox.tsx, client/src/components/Portfolio/TextBox.tsx, client/src/components/Portfolio/TextareaBox.style.ts, client/src/components/Portfolio/TextareaBox.tsx, client/src/hooks/usePatchPortfolio.ts, client/src/hooks/usePostPortfolio.ts, client/src/pages/EditPortfolio.tsx
fe-feat/newPortfolio/#63 => fe
- 제목, 소개글 글자 수 조정 (50,150글자)
- TagBox 자동완성 기능 추가
- post,patchPortfolio 시 invalid Query key 적용
- Editor 컴포넌트 화 및 조회 페이지에 적용
=> feat: Tag 자동완성 기능 및 Editor 컴포넌트화

client/src/api/client.ts, client/src/components/Detail/Comment.style.ts, client/src/components/Detail/CommentItem.style.ts, client/src/components/Detail/CommentItem.tsx, client/src/components/Detail/DetailTitle.style.ts, client/src/components/Detail/ProjectContent.style.ts, client/src/components/Detail/ProjectImg.style.ts, client/src/components/Detail/ProjectImg.tsx, client/src/components/SignUp/SignInput.style.ts, client/src/components/SignUp/SignInput.tsx, client/src/components/SignUp/SignupForm.style.ts, client/src/components/SignUp/SignupForm.tsx, client/src/hooks/usePostCheckEmail.ts, client/src/pages/Detail.tsx, client/src/types/index.ts
- 상세 페이지 레이아웃 및 기능 조정 
- 회원가입 페이지 중복 검사 기능 추가
=> feat: 상세페이지 조정

client/src/api/client.ts, client/src/components/Home/Banner.style.ts, client/src/components/Home/Banner.tsx, client/src/components/Home/Search.tsx, client/src/components/Home/Sort.tsx, client/src/components/common/Card.style.ts, client/src/components/common/Card.tsx, client/src/hooks/useAuth.ts, client/src/hooks/useGetPortfolioList.ts, client/src/hooks/useInfiniteScroll.ts, client/src/layout/footer/Footer.style.ts, client/src/layout/footer/Footer.tsx, client/src/pages/Home.tsx, client/src/types/index.ts
=> feat: api 수정 

client/src/components/User/CommentContainer.style.ts, client/src/components/User/CommentContainer.tsx, client/src/components/User/CommentItem.style.ts, client/src/components/User/CommentItem.tsx, client/src/components/User/Portfolio.tsx, client/src/components/User/UserBasicInfo.style.ts, client/src/components/User/UserBasicInfo.tsx, client/src/components/User/UserInfo.tsx, client/src/hooks/useGetUserPortfolios.ts, client/src/store/slice/editUserProfileSlice.ts, client/src/types/index.ts
fe-feat/유저페이지/#70 => fe
- CSS 수정
- 포트폴리오 데이터 전달 수정
=> design: CSS 수정

client/src/components/Detail/Comment.style.ts, client/src/components/Detail/Comment.tsx, client/src/components/Detail/CommentItem.style.ts, client/src/components/Detail/CommentItem.tsx, client/src/components/Detail/Description.style.ts, client/src/components/Detail/DetailTitle.style.ts, client/src/components/Detail/LikeBtn.style.ts, client/src/components/Detail/LikeBtn.tsx, client/src/components/Detail/ProjectContent.style.ts, client/src/components/Detail/ProjectImg.style.ts, client/src/components/Home/Banner.style.ts, client/src/components/Home/Banner.tsx, client/src/components/Login/LoginContainer.style.tsx, client/src/components/Login/LoginContainer.tsx, client/src/components/Portfolio/ImgBox.style.ts, client/src/components/Portfolio/PortfolioContainer.style.ts, client/src/components/Portfolio/TagBox.style.ts, client/src/components/Portfolio/TextareaBox.style.ts, client/src/components/Portfolio/UserBox.style.ts, client/src/components/User/CommentContainer.style.ts, client/src/components/User/UserBasicInfo.style.ts, client/src/components/User/UserEditForm.style.ts, client/src/layout/header/Hamburger.style.tsx, client/src/layout/header/Header.style.tsx, client/src/pages/AddEmail.style.ts, client/src/pages/SignUp.style.ts
fe/rickyshu => fe
- 전체 레이아웃 수정 
- 댓글 기능 수정 
- 댓글 형식 수정
- 좋아요 버튼 수정
=> feat: 레이아웃 및 기능 전체 수정

client/src/components/Login/LoginContainer.tsx, client/src/pages/AddEmail.tsx, client/src/router.tsx
fe-feat/AddEmail/#63 => fe
- addEmail 페이지 이메일 중복 기능 구현)
- addEmail 페이지 접근 처리 기능 구현(로그인한 유저, url에 userId가 없는 경우, email을 보유한 유저는 접근 불가)
=> feat: addEmail 중복확인 및 접근 처리 기능 구현

client/src/api/client.ts, client/src/components/User/CommentContainer.style.ts, client/src/components/User/CommentContainer.tsx, client/src/components/User/CommentItem.style.ts, client/src/components/User/CommentItem.tsx, client/src/components/User/Portfolio.tsx, client/src/components/User/UserBasicInfo.tsx, client/src/hooks/usePostUserComment.ts, client/src/types/index.ts
fe-feat/AddEmail/#70 => fe
- 유저 댓글 비밀글 기능 적용
- 회원정보 수정시 발생하는 github null값 적용 오류 수정
- 유저 포트폴리오 리스트가 빈배열일 경우 표시사항 수정
- 유저 댓글 CSS 수정
=> feat: 유저 댓글 비밀글 적용

client/src/pages/AddEmail.style.ts, client/src/pages/AddEmail.tsx
fe-feat/AddEmail/#66 => fe 
중복확인 버튼 위치 조정 및 수정
=> refactor: 중복 확인 버튼 수정

client/src/components/User/CommentContainer.style.ts, client/src/components/User/CommentContainer.tsx, client/src/components/User/UserDetailInfo.style.ts
fe-feat/AddEmail/#70 => fe
- 유저 댓글 작성시 비로그인 상태일 경우 에러 메세지 출력
- 유저 정보와 댓글 사이의 간격 조절
=> feat: 유저 댓글 작성시 로그인 확인

client/src/components/User/UserEditForm.tsx, client/src/hooks/useDeleteUserProfile.ts
fe-feat/AddEmail/#70 => fe
- 비동기 작업으로 인해 발생한 회원탈퇴 오류 수정
=> fix: 회원탈퇴 오류 수정

client/src/components/User/Portfolio.tsx
fe-feat/AddEmail/#70 => fe
- 전달되는 변수명 수정
=> fix: 전달되는 변수명 수정

server/src/main/java/main001/server/domain/user/entity/User.java, server/src/main/resources/application-server.yml
=> Fix: profileImg 길이 수정#219

server/src/main/java/main001/server/domain/user/entity/User.java
User 문자길이 수정
- password
- profileImg
- git&blogLink Issue #219
=> Fix: User 문자길이 수정#219

server/src/main/java/main001/server/domain/user/entity/User.java
=> Fix: profileImg 길이 수정

server/src/main/java/main001/server/domain/user/entity/User.java, server/src/main/resources/application-server.yml
MySQL 설정 수정
- sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'
- jdbcCompliantTruncation=false
Issue #232
=> Fix: MySQL 설정 수정

server/src/main/java/main001/server/domain/user/entity/User.java, server/src/main/resources/application-server.yml
- OAuth 2.0관련 리다이렉션 URL 변경
- ProfileImg 길이 수정
Issue #234
=> Be feat/deploy setting#234

client/src/components/Home/Search.tsx, client/src/hooks/useGetPortfolioList.ts, client/src/pages/Home.tsx
fe-feat/home/#71 => fe 
* 검색 옵션이 데스크탑일때와 모바일/태블릿일때 달라지는 버그 수정했습니다. 
* 안쓰는 변수 및 함수를 삭제했습니다.
=> fix: 검색 옵션이 데스크탑일때와 모바일/태블릿일때 달라지는 버그 수정

client/src/components/Home/Search.tsx, client/src/components/User/Portfolio.tsx, client/src/hooks/useGetPortfolioList.ts, client/src/hooks/useGetUserPortfolios.ts, client/src/hooks/useInfiniteScroll.ts, client/src/pages/AddEmail.tsx, client/src/pages/Home.tsx
* 데스크탑 사이즈와 모바일/태블릿 사이즈 검색 옵션 안 맞는 버그 수정 
* 유저 포트폴리오 정렬 버그 수정
=> 실물 배포 v1.0.1

client/src/hooks/useDeletePortfolio.ts, client/src/pages/Detail.tsx
rickyshu/fe =>fe 
- 로그인 안 했으면 좋아요 기능 표시 안되기 
- 작성 날짜 표시하기
- 포트폴리오 삭제 즉시 적용
=> feat: 상세 페이지 날짜 표시 및 좋아요 기능 숨기기

client/src/pages/Detail.tsx
=> fix:console 삭제

client/src/components/Detail/DetailTitle.tsx, client/src/hooks/useDeletePortfolio.ts
- fe/rickyshu =>fe
- 포트폴리오 삭제 시 즉시 적용
=> feat: 포트폴리오 삭제 시 즉시 적용

client/src/api/client.ts, client/src/components/Detail/ProjectImg.tsx, client/src/components/SignUp/SignupForm.style.ts, client/src/components/SignUp/SignupForm.tsx, client/src/layout/header/Hamburger.style.tsx, client/src/layout/header/Header.style.tsx, client/src/pages/Detail.style.ts, client/src/pages/Detail.tsx, client/src/utils/IncreasePageView.ts
rickyshu/fe =>fe
- 헤더 레이아웃 조정 
- 조회수 기능 수정 
- 조회수 및 좋아요 표시 위치 변경 
- 빈문자열 중복 검사 문제 해결
=> design: 전반적인 레이아웃 수정

client/src/components/Detail/Comment.tsx
=> feat:댓글 navbtn 숨기기 기능 추가

client/src/components/Detail/Comment.tsx
=> fix:console 제거

server/src/main/java/main001/server/domain/user/entity/User.java, server/src/main/resources/application-dev.yml
=> Chore: Username 길이수정 및 Dev 서버 세팅#253

client/src/components/SignUp/SignupForm.tsx
- rickyshu/fe  => fe
- 회원 가입 이름 9글자 이하로 제한
=> feat:회원가입 글자 수 제한 기능 추가

server/src/main/resources/application-dev.yml, server/src/main/resources/application-server.yml
=> Chore : Dev 서버 세팅#261

client/src/api/client.ts, client/src/components/Portfolio/ImgBox.tsx, client/src/components/Portfolio/PortfolioContainer.tsx, client/src/components/SignUp/SignupForm.tsx, client/src/hooks/usePatchPortfolio.ts, client/src/hooks/usePostPortfolio.ts
- fe => main
- 포트폴리오 수정 시 이미지 초기화 현상 수정
- 변경된 API에 맞게 코드 수정
=> fix: 포트폴리오 수정 시 이미지 초기화 현상 수정

client/src/App.tsx, client/src/router.tsx
=> feat: 코드 spliting을 통한 최적화
